SELECT /*+ INDEX_DESC (PROJECT, SYS_C007148) */
    P.PJTNO,
    P.PJTNM,
    DC3.DTL_CDNM AS COMPYNM,
    P.PJTFROMDATE,
    P.PJTTODATE
FROM
    PROJECT P
JOIN
    DTL_CODE DC3 ON (P.COMPYNO = DC3.DTL_CD AND DC3.CODE = 'D600')
WHERE
    P.PJTNM LIKE '%' || '0' || '%';
    
   
   
   	SELECT * FROM MEMBER;
	SELECT * FROM PROJECT;
	SELECT * FROM MEMBER_PROJECT;
	SELECT * FROM code;
	SELECT * FROM DTL_CODE;
	

SELECT /*+ INDEX_DESC (PROJECT, SYS_C007148)*/


SELECT P.PJTNM, DC6.DTL_CDNM AS COMPANYNM ,P.PJTFROMDATE ,P.PJTTODATE ,
	   M.UNO, M.UNM, P.PJTFROMDATE ,P.PJTTODATE ,MP.PJTROLE  
FROM PROJECT P
JOIN MEMBER_PROJECT MP  ON MP.PJTNO = P.PJTNO
JOIN MEMBER M ON MP.UNO = M.UNO  
JOIN DTL_CODE DC6 ON P.COMPYNO = DC6.DTL_CD AND DC6.CODE ='D600'
JOIN DTL_CODE DC7 ON MP.PJTROLE = DC7.DTL_CD AND DC7.CODE ='D700'
WHERE P.PJTNO = 11;


SELECT P.PJTNM, DC6.DTL_CDNM AS COMPANYNM, P.PJTFROMDATE AS STARTDATE, P.PJTTODATE AS ENDDATE,
       M.UNO, M.UNM, dc7.DTL_CDNM AS pjtrole, mp.PJTROLE,MP.INP_DATE  ,MP.WDP_DATE  
FROM PROJECT P
LEFT JOIN MEMBER_PROJECT MP ON MP.PJTNO = P.PJTNO
LEFT JOIN MEMBER M ON MP.UNO = M.UNO  
LEFT JOIN DTL_CODE DC6 ON P.COMPYNO = DC6.DTL_CD AND DC6.CODE ='D600'
LEFT JOIN DTL_CODE DC7 ON MP.PJTROLE = DC7.DTL_CD AND  DC7.CODE ='D700'
WHERE P.PJTNO = 11;


SELECT 
	M.UNO
	, M.UNM
	, DC2.DTL_CDNM AS JOBRANK
	, DC3.DTL_CDNM AS JOBSKILL 
FROM MEMBER M
LEFT JOIN DTL_CODE DC2 ON M.JOBRANK = DC2.DTL_CD AND DC2.CODE ='D200'
LEFT JOIN DTL_CODE DC3 ON M.JOBSKILL = DC3.DTL_CD AND DC3.CODE ='D300'
WHERE 
	NOT EXISTS (
  
    	SELECT 1 FROM MEMBER_PROJECT MP
		WHERE MP.UNO = M.UNO AND MP.PJTNO = 11
  	)
  
  AND M.ENTRDATE < '2024-01-31' 
 
  AND M.UNM LIKE '%%';


